### ISSUE TITLE
Neo4j 3.1.1 fails to start 

### ISSUE THREAD

**Issue by mwauer** [jbarrasa/neosemantics#16]
On a freshly installed Neo4j 3.1.1 (via debian.neo4j package) on Ubuntu Trusty, restarting neo4j after building and installing the plugin fails:

```
2017-02-10 12:05:59.647+0000 INFO  Starting...
2017-02-10 12:06:00.354+0000 INFO  Bolt enabled on localhost:7687.
2017-02-10 12:06:01.400+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@771a6450' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@771a6450' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@771a6450' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:227)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:28)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@771a6450' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:199)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /var/lib/neo4j/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:193)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:124)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:57)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'apoc.ApocKernelExtensionFactory$1@3e2e3142' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:189)
        ... 9 more
Caused by: java.lang.NoSuchMethodError: org.neo4j.kernel.api.proc.ProcedureSignature$Builder.mode(Lorg/neo4j/kernel/api/proc/ProcedureSignature$Mode;)Lorg/neo4j/kernel/api/proc/ProcedureSignature$Builder;
        at apoc.schema.AssertSchemaProcedure.signature(AssertSchemaProcedure.java:152)
        at org.neo4j.kernel.impl.proc.ProcedureRegistry.register(ProcedureRegistry.java:53)
        at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:103)
        at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:76)
        at apoc.ApocKernelExtensionFactory$1.start(ApocKernelExtensionFactory.java:46)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        ... 14 more
```

**Comment by mwauer** [comment]
Additionally, when setting neo4j.version to 3.1.1 in the POM, it won't compile.

**Comment by mwauer** [comment]
sorry, probably a duplicate of #12 .

**Comment by jbarrasa** [comment]
Hey, I've removed a dependency that was not required and that was bundling a Neo4j jar that caused a conflict on startup.
It should be fine now. Let me know if it works for you.

JB.

**Comment by jbarrasa** [comment]
Closing this issue, reopen if still unsolved for you.
