### ISSUE TITLE
Neo4j Not starting

### ISSUE THREAD

**Issue by nasrinazif** [jbarrasa/neosemantics#25]
Hello, When I want to start the server, I get this error:
```
C:\neo4j-enterprise-3.1.3\bin>neo4j
Usage: neo4j { console | start | stop | restart | status | install-service | uninstall-service } < -Verbose >

C:\neo4j-enterprise-3.1.3\bin>neo4j console
2017-04-06 19:46:20.699+0000 INFO  ======== Neo4j 3.1.3 ========
2017-04-06 19:46:20.902+0000 INFO  Starting...
2017-04-06 19:46:21.496+0000 INFO  Bolt enabled on localhost:7687.
2017-04-06 19:46:21.512+0000 INFO  Initiating metrics...
2017-04-06 19:46:25.492+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@66204af3' was successfully initialized, but failed to start. Please see attached cause exception. Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@66204af3' was successfully initialized, but failed to start. Please see attached cause exception.
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@66204af3' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:230)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:91)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:68)
        at org.neo4j.server.enterprise.EnterpriseEntryPoint.main(EnterpriseEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@66204af3' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:202)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\neo4j-enterprise-3.1.3\data\databases\graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:199)
        at org.neo4j.graphdb.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
        at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$1(EnterpriseNeoServer.java:91)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:89)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'apoc.ApocKernelExtensionFactory$1@e77f58c' was successfully initialized, but failed to start. Please see attached cause exception.
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:443)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.extension.KernelExtensions.start(KernelExtensions.java:86)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:195)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/api/proc/Mode
        at apoc.schema.AssertSchemaProcedure.signature(AssertSchemaProcedure.java:152)
        at org.neo4j.kernel.impl.proc.ProcedureRegistry.register(ProcedureRegistry.java:53)
        at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:103)
        at org.neo4j.kernel.impl.proc.Procedures.register(Procedures.java:76)
        at apoc.ApocKernelExtensionFactory$1.start(ApocKernelExtensionFactory.java:49)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:433)
        ... 14 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.api.proc.Mode
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 20 more

C:\neo4j-enterprise-3.1.3\bin>
```

**Comment by nasrinazif** [comment]
I updated the apoc in POM file and it is now working.

**Comment by bb-work** [comment]
@nasrinazif what version of apoc worked for you?  I'm getting the same error.

**Comment by nasrinazif** [comment]
@bb-work 3.1.2.5 worked for me

**Comment by jbarrasa** [comment]
Hey, I've added a pre-packaged jar for Neo4j 3.2 in the releases page. 
I'd recommend you upgrade to Neo4j 3.2 and copy the jar in the plugins dir. 
This should hopefully do the job. Let me know if not.

JB.

**Comment by nasrinazif** [comment]
@jbarrasa Thanks for your reply. I did that but unfortunately, I got this error:

> Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2a770ef4' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to register procedure, because the name `apoc.index.orderedByText` is already in use.".

**Comment by jbarrasa** [comment]
Hi, the pre-packaged neo4j jar already bundles apoc. So if you have it in your plugins directory it will clash. I think this is the error you are getting.

JB.

**Comment by jbarrasa** [comment]
Hi noticed there is an error in my previous comment. I meant **the pre-packaged neosemantics jar already bundles apoc**. neo4j does not, obviously.
