### ISSUE TITLE
Neo4j 3.3.1 Desktop Not starting

### ISSUE THREAD

**Issue by tariksalihovic** [jbarrasa/neosemantics#36]
Neo4j is not able to start the server. Seems the problem as in other similar issues regarding the plugin. Is the plugin available for v3.3.1 - if not how to download v3.2.0? See log code below:

`2017-12-08 10:12:52.824+0000 INFO  ======== Neo4j 3.3.1 ========
2017-12-08 10:12:52.937+0000 INFO  Starting...
2017-12-08 10:12:58.306+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2017-12-08 10:12:58.388+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@13330ac6' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@13330ac6' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@13330ac6' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@13330ac6' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\Users\00Tarik\AppData\Roaming\Neo4j Desktop\Application\neo4jDatabases\database-5af8e6ac-636d-457c-a1b7-5a9f365bf857\installation-3.3.1\data\databases\graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
	at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$1(EnterpriseNeoServer.java:75)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@64c63c79' failed to initialize. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:427)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/util/JobScheduler
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
	at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at org.neo4j.kernel.impl.util.DependenciesProxy.dependencies(DependenciesProxy.java:55)
	at org.neo4j.kernel.extension.KernelExtensions.getKernelExtensionDependencies(KernelExtensions.java:125)
	at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:58)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.impl.util.JobScheduler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
2017-12-08 10:12:58.397+0000 INFO  Neo4j Server shutdown initiated by request
2017-12-08 10:14:44.136+0000 INFO  ======== Neo4j 3.3.1 ========
2017-12-08 10:14:44.247+0000 INFO  Starting...
2017-12-08 10:14:46.613+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2017-12-08 10:14:46.663+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@37e4d7bb' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@37e4d7bb' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@37e4d7bb' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@37e4d7bb' was successfully initialized, but failed to start. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\Users\00Tarik\AppData\Roaming\Neo4j Desktop\Application\neo4jDatabases\database-5af8e6ac-636d-457c-a1b7-5a9f365bf857\installation-3.3.1\data\databases\graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
	at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$1(EnterpriseNeoServer.java:75)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.extension.KernelExtensions@3f67593e' failed to initialize. Please see the attached cause exception "org.neo4j.kernel.impl.util.JobScheduler".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:427)
	at org.neo4j.kernel.lifecycle.LifeSupport.init(LifeSupport.java:62)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:98)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: java.lang.NoClassDefFoundError: org/neo4j/kernel/impl/util/JobScheduler
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at sun.misc.ProxyGenerator.generateClassFile(ProxyGenerator.java:451)
	at sun.misc.ProxyGenerator.generateProxyClass(ProxyGenerator.java:339)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:639)
	at java.lang.reflect.Proxy$ProxyClassFactory.apply(Proxy.java:557)
	at java.lang.reflect.WeakCache$Factory.get(WeakCache.java:230)
	at java.lang.reflect.WeakCache.get(WeakCache.java:127)
	at java.lang.reflect.Proxy.getProxyClass0(Proxy.java:419)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:719)
	at org.neo4j.kernel.impl.util.DependenciesProxy.dependencies(DependenciesProxy.java:55)
	at org.neo4j.kernel.extension.KernelExtensions.getKernelExtensionDependencies(KernelExtensions.java:125)
	at org.neo4j.kernel.extension.KernelExtensions.init(KernelExtensions.java:58)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.init(LifeSupport.java:406)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.neo4j.kernel.impl.util.JobScheduler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
2017-12-08 10:14:46.667+0000 INFO  Neo4j Server shutdown initiated by request
WARNING: This command does not appear to be running with administrative rights.  Some commands may fail e.g. Start/Stop
2017-12-08 10:25:48.071+0000 INFO  ======== Neo4j 3.3.1 ========
2017-12-08 10:25:48.140+0000 INFO  Starting...
2017-12-08 10:25:49.903+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2017-12-08 10:25:49.929+0000 INFO  Initiating metrics...
2017-12-08 10:25:57.848+0000 INFO  Started.
2017-12-08 10:25:58.171+0000 INFO  Mounted REST API at: /db/manage
2017-12-08 10:26:00.119+0000 INFO  Remote interface available at http://localhost:7474/
WARNING: This command does not appear to be running with administrative rights.  Some commands may fail e.g. Start/Stop
2017-12-08 10:33:01.412+0000 INFO  ======== Neo4j 3.3.1 ========
2017-12-08 10:33:01.469+0000 INFO  Starting...
2017-12-08 10:33:03.343+0000 INFO  Bolt enabled on 127.0.0.1:7687.
2017-12-08 10:33:03.378+0000 INFO  Initiating metrics...
2017-12-08 10:33:10.539+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2a4cb8ae' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2a4cb8ae' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2a4cb8ae' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
	at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
	at org.neo4j.server.enterprise.CommercialEntryPoint.main(CommercialEntryPoint.java:22)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@2a4cb8ae' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
	... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, C:\Users\00Tarik\AppData\Roaming\Neo4j Desktop\Application\neo4jDatabases\database-5af8e6ac-636d-457c-a1b7-5a9f365bf857\installation-3.3.1\data\databases\graph.db
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
	at org.neo4j.kernel.enterprise.EnterpriseGraphDatabase.<init>(EnterpriseGraphDatabase.java:36)
	at org.neo4j.server.enterprise.EnterpriseNeoServer.lambda$static$1(EnterpriseNeoServer.java:75)
	at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@5ac646b3' was successfully initialized, but failed to start. Please see the attached cause exception "Cannot inherit from final class".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
	... 9 more
Caused by: java.lang.VerifyError: Cannot inherit from final class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:141)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:118)
	at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
	at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:91)
	at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:82)
	at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:275)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
	... 11 more
2017-12-08 10:33:10.579+0000 INFO  Neo4j Server shutdown initiated by request`

**Comment by ivmreg** [comment]
I was able to resolve it by cloning the repo and modifying the pom.xml as noted in this comment:
https://github.com/jbarrasa/neosemantics/issues/17#issuecomment-300687165

In my case (Windows, Neo4j from zip file, version 3.3.1) the contents of pom.xml were (first 30 lines):

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.neo4j</groupId>
	<artifactId>neosemantics</artifactId>
	<version>3.2.1.1-SNAPSHOT</version>
	<properties>
		**<neo4j.version>3.3.1</neo4j.version>**
		<sesame.version>4.1.1</sesame.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.neo4j</groupId>
			<artifactId>neo4j</artifactId>
			<version>${neo4j.version}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
		    <groupId>org.neo4j</groupId>
		    <artifactId>server-api</artifactId>
		    <version>${neo4j.version}</version>
            <scope>provided</scope>
		</dependency>
		**<dependency>
			<groupId>org.neo4j.procedure</groupId>
			<artifactId>apoc</artifactId>
			<version>3.3.0.1</version>
		</dependency>**
```

I had to modify the version for Neo4j (1st edit) and add an additional org.neo4j.procedure -> apoc dependency (apoc version 3.3.0.1)

After this you have to build the package using maven - "mvn clean build".

Some of the unit tests were failing due to what I understand a different signature (in neo4j) in some of the methods that tests use. I commented them out just to get the build going.

The build completed successfully and I got a working jar.

**Comment by jbarrasa** [comment]
Hi, I've created a new 3.3 branch and added a new release.
