### ISSUE TITLE
Cannot run both neosemantics and apoc as plugins

### ISSUE THREAD

**Issue by agiesler** [jbarrasa/neosemantics#45]
Hi, 
I'm using neosemantics as a nice tool to import RDF based provenance graph data to neo4j. Additionally, I wanted to use apoc. Unfortunately, it seems that neo4j cannot be started with both neosemantics and apoc installed in the plugins directory:

neo4j community version 3.3.2
neosemantics 3.2.1.1
apoc release 3.3.0.1 (tested with provided binary and locally built jar)

Linux machine

It runs with neosemantics installed alone, and with apoc installed alone, but not concurrently. Do you have an idea? Here is the error log ...

2018-02-16 15:22:23.904+0000 INFO  Starting...
2018-02-16 15:22:26.719+0000 INFO  Bolt enabled on 0.0.0.0:7015.
2018-02-16 15:22:35.374+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7715d43c' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;". Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7715d43c' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
org.neo4j.server.ServerStartupException: Starting Neo4j failed: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7715d43c' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
        at org.neo4j.server.exception.ServerStartupErrors.translateToServerStartupError(ServerStartupErrors.java:68)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:219)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:111)
        at org.neo4j.server.ServerBootstrapper.start(ServerBootstrapper.java:79)
        at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:32)
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.server.database.LifecycleManagingDatabase@7715d43c' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.server.AbstractNeoServer.start(AbstractNeoServer.java:211)
        ... 3 more
Caused by: java.lang.RuntimeException: Error starting org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory, /usr/local/neo4j/neo4j-community-3.3.2/data/databases/graph.db
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:211)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:126)
        at org.neo4j.server.CommunityNeoServer.lambda$static$0(CommunityNeoServer.java:58)
        at org.neo4j.server.database.LifecycleManagingDatabase.start(LifecycleManagingDatabase.java:88)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 5 more
Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.proc.Procedures@4d21b505' was successfully initialized, but failed to start. Please see the attached cause exception "class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;".
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
        at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
        at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:207)
        ... 9 more
Caused by: java.lang.VerifyError: class com.fasterxml.jackson.databind.deser.SettableBeanProperty$Delegating overrides final method getDeclaringClass.()Ljava/lang/Class;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:141)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader$1.fetchNextOrNull(ProcedureJarLoader.java:118)
        at org.neo4j.collection.PrefetchingRawIterator.peek(PrefetchingRawIterator.java:50)
        at org.neo4j.collection.PrefetchingRawIterator.hasNext(PrefetchingRawIterator.java:36)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java:91)
        at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoader.java:82)
        at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:275)
        at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:445)
        ... 11 more
2018-02-16 15:22:35.378+0000 INFO  Neo4j Server shutdown initiated by request

Thanks, André

**Comment by pmahend1** [comment]
Same issue.

I had raised [issue](https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/743) APOC github, but seems its an issue with NeoSemantics

**Comment by jbarrasa** [comment]
Well, actually it's an incompatibility between APOC and Neosemantics. Each library work OK separately but not when deployed together :) 
I've just merged a PR from @ikwattro to fix this problem. There was a conflict in the versions of Jackson used by the JSON-LD parser in Sesame and the one used by APOC. It should be fine now, although I've not added a new release yet so you'll need to build from source for now.
Hope this helps.

**Comment by agiesler** [comment]
Thanks a lot for investing your time in that fix! It's working now with APOC for me.

**Comment by Tin-Nguyen** [comment]
@jbarrasa I'm facing the same issue with my owned plugin and neo4j-streams. My owned plugin doesn't use Jackson. Can you let me know how we did resolve?
