### ISSUE TITLE
Latest code does not deploy smoothly

### ISSUE THREAD

**Issue by wadael** [jbarrasa/neosemantics#5]
I get an exception on neo4j restart to take neosemantics jar into account

Caused by: org.neo4j.kernel.api.exceptions.ProcedureException: Procedures must return a Stream 
of records, where a record is a concrete class
that you define and not a Stream<?>.
    at org.neo4j.kernel.impl.proc.OutputMappers.mapper(OutputMappers.java:162)
    at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler.compileProcedure(ReflectivePr
ocedureCompiler.java:106)
    at org.neo4j.kernel.impl.proc.ReflectiveProcedureCompiler.compile(ReflectiveProcedureCo
mpiler.java:84)
    at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProcedures(ProcedureJarLoader.java
:88)
    at org.neo4j.kernel.impl.proc.ProcedureJarLoader.loadProceduresFromDir(ProcedureJarLoad
er.java:77)
    at org.neo4j.kernel.impl.proc.Procedures.start(Procedures.java:125)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:434)
    ... 12 more
nohup: les entrées sont ignorées

Therefore, call dbms.procedures() only shows   semantics.runConsistencyChecks
Using neo 3.0.6, Java8 on linux64

**Comment by jbarrasa** [comment]
Hi wadael, I cannot reproduce the behavior your describe.
I've checked in a significant number of changes, would you mind pulling the new code and retrying?
If the problem persists it may be worth attaching the whole log for me to investigate?
Thanks!

JB.

**Comment by wadael** [comment]
Got the latest code. 
I cannot reproduce this either.
